person:
    name: xiaoming${random.uuid}
    age: 12
    happy: true
    birth: 2019/02/02
    maps: {a: "1", b: "2"}
    lists:
        - a
        - b
        - c
    dog:
        name: xiaogou
        age: 4


server:
    port: 8080
spring:
    profiles:
        active: dev
        include:
---
server:
    port: 8081
spring:
    profiles: dev

---
server:
    port: 8082
spring:
    profiles: test

#可以通过 debug=true来查看，那些自动配置类生效，哪些没有生效。
debug: true